### ISSUE TITLE
python-pykeepass 4.0.0

### ISSUE THREAD

**Issue by ghost** [viczem/ansible-keepass#19]
I just updated to the new version and the lookup no longer works. So a downgrade to version 3.2.1 is necessary as mentioned in the README.

Are you already aware of the new version/problem?

**Comment by viczem** [comment]
Yes, sure. It will be fixed in near future

**Comment by warpcode** [comment]
I did a bit of playing on this and found 2 things

Firstly i needed to add
```
try:
    FileNotFoundError
except NameError:
    FileNotFoundError = IOError
```
To prevent an error about FileNotFoundError not being defined

Secondly, it looks as though PyKeePass now accepts a list as the path parameter
```
e.g
['path', 'to', 'entry']
```

For now I have this working as
```
entry = LookupModule.keepass.find_entries(path=entry_path.split('/'))
```
