### ISSUE TITLE
 global name 'FileNotFoundError'

### ISSUE THREAD

**Issue by jaysolanki918** [viczem/ansible-keepass#21]
Hi , I've been trying to use the example playbook to test the example but i keep getting  'global name 'FileNotFoundError'' error, Below is my playbook content, could you please help identify what could be wrong?

- name: Example
  hosts: localhost
  connection: local
#    keepass_psw : password. [optional] if the socket is used
#    keepass_key : [optional] path to keyfile
  vars:
    keepass_dbx : "./example.kdbx"
     spam_login: "{{ lookup('keepass', 'spam', 'User Name')}}"
     spam_password: "{{ lookup('keepass', 'spam', 'password')}}"
    ham_login: "{{ lookup('keepass', 'example/ham', 'User Name') }}"
    ham_password: "{{ lookup('keepass','example/ham', 'password')}}"
    pork_custom_property: "{{ lookup('keepass', 'example/pork', 'pork_custom_property', true)}}"
    pork_all_custom_properties: "{{ lookup('keepass', 'example/pork', '*', true)}}"

  tasks:
     - debug:
         msg: "fetch group: /    username: {{ spam_login }}    password: {{ spam_password }}"

    - debug:
        msg: "fetch group: /example/ham     username: {{ ham_login }}   password: {{ ham_password }}"

    - debug:
        msg: "fetch group: /example/pork     pork_custom: {{ pork_custom_property }}"

    - debug:
        msg: "fetch group: /example/pork     pork_all_custom_properties: {{ pork_all_custom_properties }}"

**Comment by viczem** [comment]
Hi, try to use Python 3
