### ISSUE TITLE
Plugin does not suppport lookup of properties/attributes with several lines

### ISSUE THREAD

**Issue by lfvjimisola** [viczem/ansible-keepass#28]
The lookup of a property with several (multi) lines is an empty string.

It works with pykeepass in interpreter.

**Comment by lfvjimisola** [comment]
Thank you for the fast reply and fix!

May I ask if there are any plans of supporting attachments? That it, save an attachment in KeePass to disk.

Understand that it quite certainly can't be part of the lookup but maybe as a task (own module)?
With the ansible-galaxy fix it might not be to much work?

**Comment by viczem** [comment]
I think it is simply to add a possibility for reading attachments to variables. But what use case? 
We can continue to discuss it by email

**Comment by lfvjimisola** [comment]
> I think it is simply to add a possibility for reading attachments to variables. But what use case? We can continue to discuss it by email

The problem is when the file in binary and also how large can variables be?

Email or that we create another issue?

**Comment by viczem** [comment]
Variables are stored a data in memory, therefore should be dependent on RAM. 

Perhaps I do not fully understand your idea, I can assume that you want to have an encrypted binary file. You can encrypt a file with standard Ansible tools and decrypt it when you need - https://docs.ansible.com/ansible/latest/user_guide/vault.html#using-encrypted-variables-and-files.

I've never done this before, I hope this helps you

**Comment by lfvjimisola** [comment]
Yes, in theory unless Ansible has made any restrictions themselves. But, I haven't found any ([link](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html)).

That said, I've written a module for writing attachments to file system (see #29)
