### ISSUE TITLE
Concurrent access on testing socket file and creating associated process

### ISSUE THREAD

**Issue by JulienBell** [viczem/ansible-keepass#36]
When using lookup plugin keepass on a group with multiple host, we have a race condition on creating the command process and pipeline socket. Only one host succeed in lookup data in that case, others that are in the race condition failed.

It is due to the following line code that could be walked in a race condition:
https://github.com/viczem/ansible-keepass/blob/107fb09a1a831fd2ada3de86becc3522066f80cf/plugins/lookup/keepass.py#L94

The previous opening file action should be protect by a lock or mutex while the socket file is not actually created

**Comment by JulienBell** [comment]
I just see that my collection version is 0.7.0 and not the last one, may be my runtime concurrent issue is not link to my previous code analysis...

**Comment by viczem** [comment]
This issue has been resolved in version 0.7.2

**Comment by JulienBell** [comment]
Ok, I'll try.

I still thinking that, if the plugin is run in multithreading, the following section should be threadsafe protect thanks  a Lock():

   ```
    lock_op.acquire() 
    try:
            os.open(lock_file_, os.O_RDWR)
        except FileNotFoundError:
            cmd = [
                "/usr/bin/env",
                "python3",
                os.path.abspath(__file__),
                var_dbx,
                socket_path,
                var_ttl,
            ]
            if var_key:
                cmd.append("--key=%s" % var_key)
            try:
                display.v("KeePass: run socket for %s" % var_dbx)
                subprocess.Popen(cmd)
            except OSError:
                os.remove(lock_file_)
                raise AnsibleError(traceback.format_exc())

            attempts = 10
            success = False
            for _ in range(attempts):
                try:
                    display.vvv("KeePass: try connect to socket %s/%s" % (_, attempts))
                    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
                    sock.connect(socket_path)
                    # send password to the socket for decrypt keepass dbx
                    display.vvv("KeePass: send password to '%s'" % socket_path)
                    sock.send(_rq("password", str(var_psw)))
                    resp = sock.recv(1024).decode().splitlines()

                    if len(resp) == 2 and resp[0] == "password":
                        if resp[1] == "0":
                            success = True
                        else:
                            raise AnsibleError("KeePass: wrong dbx password")
                    sock.close()
                    break
                except FileNotFoundError:
                    # wait until the above command open the socket
                    time.sleep(1)

            if not success:
                raise AnsibleError("KeePass: socket connection failed for %s" % var_dbx)

            display.v("KeePass: open socket for %s -> %s" % (var_dbx, socket_path))

    finally:
        lock_op.release()

```

Don't you think so ?

**Comment by viczem** [comment]
It protected:
- [`lock` function](https://github.com/viczem/ansible-keepass/blob/107fb09a1a831fd2ada3de86becc3522066f80cf/plugins/lookup/keepass.py#L412)
- [usage](https://github.com/viczem/ansible-keepass/blob/main/plugins/lookup/keepass.py#L453)

Part of the plugin code from your example used to avoid manually opening keepass socket before use Ansible

**Comment by JulienBell** [comment]
Yes, but you may start multiple subprocess, and one will win to acquire le fd lock. 
So, don't we have unused subprocess  waiting on the lock, and on the ttl expiration they could unblock and restart listening on sock ?

**Comment by viczem** [comment]
If one subprocess has a lock (can be only one), others will terminate. On the ttl expiration, the subprocess will terminate and remove lock file and socket file.

**Comment by JulienBell** [comment]
Ok, thx for your time
